### ISSUE TITLE
Console Hang when you don´t set value in the jsAsyncWaitTimeout key

### ISSUE THREAD

**Issue by Jhara** [joescii/sbt-js-test#9]
If you don´t use the key jsAsyncWaitTimeout with a value and an error occurs the console hang

I must kill process than runs console.

![console](https://cloud.githubusercontent.com/assets/9939160/16541465/32963108-4049-11e6-9fb7-9fa8e1afdaa5.PNG)

**Comment by joescii** [comment]
That is precisely the expected behavior per the [README](https://github.com/joescii/sbt-js-test#asynchronously-loaded-assets). Either `jsAsyncWaitTimeout` must be configured or (preferably) `window.sbtJsTest.readyForTestsToRun` needs to be set to `true` in the javascript environment once assets are loaded.
